apiVersion: apps/v1
kind: Deployment
metadata:
  name: sum-app

spec:
  replicas: 3 

  selector:
    matchLabels:
      app: sum-app
      
  template:
    metadata:
      labels:
        app: sum-app


    spec:      
      containers:
        - name: sum-app
          image: sum-app:latest
          ports:
            - containerPort: 3000
