apiVersion: v1
kind: Service
metadata:
  name: sum-app-service 

spec:
  type: NodePort

  selector:
    app: sum-app

  ports:
    - protocol: TCP 
      port: 3000
      targetPort: 3000  
      nodePort: 30001